### PR TITLE
use django-appmedia

### PR DESCRIPTION
**Pull request by bclermont**
I changed setup.py and admin.py to ship javascript in the app and be able to use django-appmedia.

feel free to ignore the debian packaging!

### CODE REVIEW

**Comment by piotrkilczuk** [comment]
Thanks, I hope to merge this tomorrow!

**Comment by piotrkilczuk** [comment]
Actually the latest code in the development branch was improved for Django 1.3 compatibility (moved to static folder, symlinked as media). Therefore django-appmedia isn't really necessary, as far as I understand that app.

I like the Debian packaging and the description correction. 

P.S. Current development is done on develop branch, not master.

Should I cherrypick the desired commits or are you willing to do another pull request to the develop branch?

**Comment by bclermont** [comment]
Feel free to pick the changes you want. I'm still in django 1.2.x so I need to use django-appmedia :)

**Comment by piotrkilczuk** [comment]
OK, I decided to pick 293d90f setup.py addition, as I think, that this app is too tiny to use system packaging, now that we have pip (nothing against Debian personally).

As far as I believe, django-inline-ordering will work with django-appmedia, since there is a media dir in the app. Or will there be path issues? If so, maybe they can be resolved with a symlink?

**Pull request closed without merging**
